server:
  port: 8080
  
spring:
  application:
    name: API-GATEWAY

  data:
    mongodb:
      database: pharmachain
      host: localhost
      port: 27017
      auto-index-creation: false
      #username: root
      #password: root

  jackson:
    default-property-inclusion: non-null

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

zuul:
  ignored-services: '*'
  prefix: /api
  strip-prefix: false
  routes:
    product-service:
      path: /products/**
      service-id: PRODUCT-SERVICE
    order-service:
      path: /orders/**
      service-id: ORDER-SERVICE
  host:
    socket-timeout-millis: 30000