server:
  port: 8880
  
spring:
  application:
    name: product-service

  data:
    mongodb:
      database: pharmachain
      host: localhost
      port: 27017
      auto-index-creation: false
      #username: root
      #password: root

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true